import { vueTpNote } from "./class_tpNote.js";
vueTpNote.init({ edtNom: document.querySelector('[id=edt_nom]'),
    edtPrenom: document.querySelector('[id=edt_prenom]'),
    niveauEtude: document.querySelector('[id=edt_etude]'),
    radioMadame: document.querySelector('[id=radio_madame]'),
    radioMonsieur: document.querySelector('[id=radio_monsieur]'),
    btnAjouter: document.querySelector('[id=btn_ajouter]'),
    btnAnnuler: document.querySelector('[id=btn_annuler]'),
    btnRetirer: document.querySelector('[id=btn_retirer]'),
    btnValider: document.querySelector('[id=btn_valider]'),
    chkExpert: document.querySelector('[id=chk_expert]'),
    divFormulaire: document.querySelector('[id=div_formulaire]'),
    listePersonnel: document.querySelector("[id=select_personnel]"),
    titre: document.querySelector('[id=titre]'),
    nombrePersonnel: document.querySelector('[id=nb_personnes]')
});
/* ,divRecap :document.querySelector('[id=div_recap]')
,divFormBoutons:document.querySelector('[id=div_formulaire_boutons]')
,edtDtNais :document.querySelector('[id=edt_dtnais]')
,listeDiplome :document.querySelector('[id=select_diplome]')
,edtExperience :document.querySelector('[id=edt_experience]')
,chkWindows :document.querySelector('[id=chk_windows]')
,chkLinux :document.querySelector('[id=chk_linux]')
,chkAutre :document.querySelector('[id=chk_autre]')
,edtAutre :document.querySelector('[id=edt_autre]')
,edtCommentaire:document.querySelector('[id=edt_commentaire]')
,listeRecap :document.querySelector('[id=select_recap]')
,btnCorriger :document.querySelector('[id=btn_corriger]') */ 
//# sourceMappingURL=tpNote.js.map